Issue/#76 filter constructie
VNG-Realisatie/notificaties-api pull request #124
Opened 2022-08-01 11:44 UTC by MatthijsBekendam

refers to: https://github.com/VNG-Realisatie/notificatieservices/issues/76

2022-08-02 09:00 UTC, SonnyBA requested changes

2022-08-03 10:03 UTC, SonnyBA requested changes
Zou je ook nog tests willen toevoegen voor de `Prefix` en `Suffix` filters? Ik vroeg me daarnaast af of je ook al had nagedacht over het scenario waarin meerdere keren dezelfde key wordt opgegeven in een filter?

2022-08-04 13:19 UTC, SonnyBA requested changes
Volgens mij zijn we er bijna, check nog even de comment over de `.get`

2022-08-04 13:19 UTC, SonnyBA commented on src/nrc/api/filters.py
> +            if not event_data[event_attr] == self.node.get(event_attr, {}):
De `.get(event_attr, {})` is hier niet nodig, je loopt hier namelijk al over de `keys` in de filter heen (en weet dus dat de `key` aanwezig is)

2022-08-04 13:19 UTC, SonnyBA commented on src/nrc/api/filters.py
> +            if not event_data[event_attr].endswith(self.node.get(event_attr, {})):
Zie comment hierboven over de `.get`

2022-08-04 13:19 UTC, SonnyBA commented on src/nrc/api/filters.py
> +            if not event_data[event_attr].startswith(self.node.get(event_attr, {})):
Zie comment hierboven over de `.get`

2022-08-16 09:30 UTC, SonnyBA commented
@MatthijsBekendam kun je deze PR ook even rebasen? Hier staan wijzigingen in die niet onderdeel zijn van het ticket

2022-08-16 10:54 UTC, MatthijsBekendam commented on src/nrc/api/filters.py
> +        event_attribute = self._get_event_attribute(event, list(self.node.keys())[0])
Om de juiste event key te krijgen heb je toch de node key nodig?

2022-08-17 09:01 UTC, SonnyBA requested changes

2022-08-17 10:41 UTC, MatthijsBekendam commented on src/nrc/api/filters.py
> +            if not event_data[event_attr] == self.node.get(event_attr):
Als ik het goed zie bepaald de super() of er een match is in attribute. We moeten dan toch ook de value checken?

2022-08-17 10:41 UTC, MatthijsBekendam commented on src/nrc/api/filters.py
> +            if not event_data[event_attr] == self.node.get(event_attr):
dat gebeurt met de .get

2022-08-17 11:53 UTC, SonnyBA commented on src/nrc/api/filters.py
> +            if not event_data[event_attr] == self.node.get(event_attr):
Er moet uiteraard voor de waarde worden gecheckt maar waar ik hier op doelde was dat je de `.get` gebruikt als je niet weet of een `dict` een bepaalde `key`/`value` heeft. Als je de `evaluate` in de `super` klasse bekijkt zie je dat op het moment dat je dit stukje code bereikt, je zeker weet dat het `Event` het attribuut uit `event_attr` heeft. Met andere woorden, je kan hier altijd `self.node[event_attr]` gebruiken in plaats van `self.node.get(event_attr)`.

2022-08-17 12:09 UTC, MatthijsBekendam commented on src/nrc/api/filters.py
> +            if not event_data[event_attr] == self.node.get(event_attr):
aah oke, nu snap ik hem :)

2022-08-17 12:41 UTC, SonnyBA approved these changes

2022-09-01 12:39 UTC, merged